blank_issues_enabled: false
contact_links:
  - name: Need Support?
    url: https://github.com/yaqiin/quran/discussions
    about: Please ask and answer questions in Discussions instead of opening an issue.
